# These are supported funding model platforms

github: [ cnheider ]
patreon:         cnheider
open_collective: cnheider
ko_fi:           cnheider
tidelift:        pypi/heimdallr
custom: # Replace with a single custom sponsorship URL
